### ISSUE TITLE
Add endpoint for surfacing 'latest' test run

### ISSUE THREAD

**Issue by lukebjerring** [w3c/wptdashboard#161]
The endpoint could help us determine state-changes for test runs (i.e. detect when a PR is changing the state of a test to be failing when it was passing).
(See https://github.com/w3c/web-platform-tests/issues/7475 for context)

e.g. it would be nice if instead of 
https://storage.googleapis.com/wptd/b12daf6ead/safari-10-macos-10.12-sauce/IndexedDB/abort-in-initial-upgradeneeded.html
we could just call 
https://storage.googleapis.com/wptd/latest/safari-10-macos-10.12-sauce/IndexedDB/abort-in-initial-upgradeneeded.html
where latest works out what to load.

If we can't do so in cloud storage's API, we can add an endpoint somewhere like wpt.fyi/lastest/[test name]

**Comment by jeffcarp** [comment]
Deployed #166, however it looks like we're missing a datastore index:

https://wpt.fyi/latest/chrome-63.0-linux

I haven't double checked but I think adding this to `index.yaml` will resolve the issue:

```
- kind: TestRun
  properties:
  - name: BrowserVersion
  - name: OSName
  - name: CreatedAt
    direction: desc
- kind: TestRun
  properties:
  - name: BrowserVersion
  - name: OSName
  - name: OSVersion
  - name: CreatedAt
    direction: desc
```
